# Generated by Django 5.0.8 on 2024-08-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CapturedPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.CharField(max_length=15)),
                ('dst_ip', models.CharField(max_length=15)),
                ('protocol', models.CharField(max_length=10)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField()),
            ],
        ),
    ]
